// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AttachmentType } from "./AttachmentType";

/**
 * @description 定义附件的核心数据结构。
 */
export type Attachment = { id: bigint, task_id: bigint, attachment_type: AttachmentType, payload: string, };
