// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * @description 定义任务的优先级。
 * 使用一个枚举来确保类型安全，避免在代码中使用“魔术数字”。
 * `#[derive(...)]` 宏自动实现了许多有用的功能。
 */
export type Priority = "None" | "Low" | "Medium" | "High";
