// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 项目的领域模型，定义了一个“项目”或“分类”的核心属性。
 */
export type Project = { id: bigint, name: string, created_at: string, updated_at: string, };
