// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 提醒事项的领域模型
 */
export type Reminder = { id: bigint, task_id: bigint, 
/**
 * 精确的提醒时间 (UTC)
 */
remind_at: string, 
/**
 * 是否已发送
 */
is_sent: boolean, };
