// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Priority } from "./Priority";

/**
 * 核心业务模型：任务
 * 它代表了一个待办事项的完整信息，是领域驱动设计（DDD）中的“领域对象”。
 */
export type Task = { 
/**
 * 任务的唯一标识符，使用 `i64` 以匹配数据库的 `INTEGER` 类型，并能容纳大量数据。
 */
id: bigint, 
/**
 * 任务的标题。
 */
title: string, 
/**
 * 任务的详细描述。
 */
description: string | null, 
/**
 * 任务是否已完成。
 */
is_completed: boolean, 
/**
 * 任务所属项目的 ID。
 */
project_id: bigint | null, 
/**
 * 父任务的ID。
 */
parent_id: bigint | null, subtask_count: bigint, 
/**
 * 优先级
 */
priority: Priority, 
/**
 * 任务的截止日期。
 */
due_date: string | null, 
/**
 * 最近一次未发送的提醒时间 (如果有的话)
 */
next_reminder_at: string | null, 
/**
 * 使用 `chrono` 的 `DateTime<Utc>` 来确保所有时间戳都使用统一的世界协调时（UTC）。
 * 这是处理时间的最佳实践，可以避免因用户本地时区不同而导致的数据混乱。
 */
created_at: string, updated_at: string, };
